name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Glitch
        env:
          GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
        run: |
          curl -v -X POST "https://api.glitch.com/project/githubImport" \
          -H "Authorization: ${GLITCH_TOKEN}" \
          -d "{\"projectId\":\"${GLITCH_PROJECT_ID}\", \"repo\":\"johnmarky08/kiro-ai\"}"
